name: robot-build (soft)
on: { push: { branches: ['robot/**'] } }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_test:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install (non-blocking)
        run: |
          set +e
          npm ci 2>&1 || true
          python -m pip install -U pip 2>&1 || true
          pip install -r requirements.txt 2>&1 || true
      - name: Lint & Test (non-blocking)
        run: |
          set +e
          npm run lint 2>&1 || true
          npm test --yes 2>&1 || true
          pytest -q 2>&1 || true
      - name: Summarize
        run: |
          echo "### robot soft build ✅ (gagal tidak memerah)" >> $GITHUB_STEP_SUMMARY
